### ISSUE TITLE
cdnjs version not working

### ISSUE THREAD

**Issue by munsocket** [mrdoob/stats.js#100]
It seems that cdnjs version not cached properly from github.

Reproduction steps::
1) add <script src="https://cdnjs.cloudflare.com/ajax/libs/stats.js/r16/Stats.min.js"></script>
2) insert code
```
var stats = new Stats();
stats.showPanel( 1 );
document.body.appendChild( stats.dom );
```
3) get an error: `Uncaught TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.`

**Comment by furey** [comment]
Hi @munrocket,

I was just experiencing the same issue.

As a workaround, try a version served by [unpkg.com](https://unpkg.com/stats), e.g.:

```
https://unpkg.com/stats.js@0.17.0/build/stats.min.js
```

Hope that helps!

🤓👍

**Comment by munrocket** [comment]
Nah, I write my on benchmark library 😅
https://github.com/munrocket/gl-bench
