### ISSUE TITLE
Unexpected token 'export' in r17 cdnjs version

### ISSUE THREAD

**Issue by huarse** [mrdoob/stats.js#107]
last line in r17: 

```js
export { Stats as default };
```
last line in r16: 

```js
if ( typeof module === 'object' ) {
  module.exports = Stats;
}
```

**Comment by cristea2017** [comment]
You need to include the file with a type attribute set to "module":

<script type="module" src="module.js"></script>

This worked for me

**Comment by mrdoob** [comment]
Yes, r17 was the first release as a es6 module. (This happened 5 years ago already: https://github.com/mrdoob/stats.js/pull/72)

If you're not able to use es6 modules you should continue using r16.
