### ISSUE TITLE
Failed to execute 'drawImage' on 'CanvasRenderingContext2D'

### ISSUE THREAD

**Issue by SET001** [mrdoob/stats.js#108]
for some reason, when I try to use stats it throw such an error:
`index.js:91339 Uncaught (in promise) DOMException: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.`

The way I'm using it in code is pretty much like in readme example:

```
import * as Stats from 'stats.js'

var stats = new Stats();
  
stats.showPanel( 1 );
document.body.appendChild( stats.dom );

const run = () => {
  stats.begin();
  stats.end();
  requestAnimationFrame(run);
}
requestAnimationFrame(run)
```

here is the dom structure, canvas indeed has 0 width and height:
![ssssasdss](https://user-images.githubusercontent.com/30506/69311655-84db8380-0c35-11ea-8b64-23cb3b601b35.png)

Experiencing this on Chrome: Version 76.0.3809.100 (Official Build) (64-bit)

**Comment by SET001** [comment]
Updated Chrome to Version 78.0.3904.108 (Official Build) (64-bit), but error is the same.

**Comment by mrdoob** [comment]
Sorry, no idea.

**Comment by SET001** [comment]
best issue solver ever
