### ISSUE TITLE
Customizing coloring

### ISSUE THREAD

**Issue by zephyo** [mrdoob/stats.js#112]
I saw this closed issue https://github.com/mrdoob/stats.js/issues/58 

But there's no instructions on how to customize it via CSS. In fact, I don't even know how you would customize a canvas with CSS.

It seems as though https://github.com/mrdoob/stats.js/blob/master/examples/custom.html is trying to do something with coloring, but when I use it, it just shows the default coloring.

Would really love this feature! The neon colors sometimes clashes with the aesthetics of my project.

**Comment by mrdoob** [comment]
You could try using css filters:

```js
stats.dom.style.filter = 'grayscale(100%)';
```

**Comment by zephyo** [comment]
Thanks for the suggestion! I ended up just making a copy of stats.js with color changes in the following area:
```
  // Custom code - change colors
  var fpsPanel = addPanel(new Stats.Panel("FPS", "#fff", "#000"));
  var msPanel = addPanel(new Stats.Panel("MS", "#6af", "#000"));

  if (self.performance && self.performance.memory) {
    var memPanel = addPanel(new Stats.Panel("MB", "#fad", "#000"));
  }

```

**Comment by mrdoob** [comment]
Even simpler! 👍
