### ISSUE TITLE
How do you add this?

### ISSUE THREAD

**Issue by smammadov1994** [mrdoob/stats.js#113]
I am watching a PluralSight video and I don't know how to add this js file to my django project using threejs. Do I download the whole repo and throw it into my django app?

**Comment by mrdoob** [comment]
No need to download the whole repo.
Just download [stats.js](https://github.com/mrdoob/stats.js/raw/master/build/stats.js) (or [stats.module.js](https://github.com/mrdoob/stats.js/raw/master/build/stats.module.js) if you're using [es modules](https://javascript.info/modules-intro)).
