### ISSUE TITLE
Feature request: Show multiple Panels at once

### ISSUE THREAD

**Issue by Kritten** [mrdoob/stats.js#115]
Why is it not possible to enable multiple panels with `showPanel`?
All the stats are calculated either way and I'm currently simply setting `display:block` to the panels I need.

But wouldn't  it be better to, for example, allow to pass multiple panel ids to `showPanel`?

If there are no reasons against this feature I would be happy to create a PR for this

**Comment by jasondyoungberg** [comment]
Another solution is to set `left:80`

**Comment by mordakae** [comment]
I just set it to "position: absolute; float: left;" and that works fine for me. This way I can have all the tabs I want. I also recommend adding them to their own div with a zindex: 1000 or something just to make sure they are in the foreground.

**Comment by nuthinking** [comment]
It is relatively easy to show multiple panels with the current implementation:

```javascript
const panels = [0, 2]; // 0: fps, 1: ms, 2: mb
Array.from((stats.dom as HTMLDivElement).children).forEach((child, index) => {
  (child as HTMLCanvasElement).style.display = panels.includes(index) ? 'inline-block' : 'none';
});
document.body.appendChild(stats.dom);
```
