### ISSUE TITLE
ReferenceError: Stats is not defined

### ISSUE THREAD

**Issue by lengwe** [mrdoob/stats.js#116]
Hi there!. I am trying to use this module in my javascript. However I try to add this module using the followings in my html file.
```
<script src="https://mrdoob.github.io/stats.js/build/stats.module.js"></script>
or
<script src="/js/stats.min.js"></script>
or
<script src="/js/stats.module.js"></script>
```

However, they all gave me error says `ReferenceError: Stats is not defined` and there is an error also occured saying that `Uncaught SyntaxError: Unexpected token 'export` when I try to use the `stats.module.js` file.

Anybody knows what the problem is?

**Comment by virafpatrawala** [comment]
Try this, it works for me:
First
`npm install stats-js`

Then
`import Stats from 'stats-js';`

And then proceed as usual...
`const stats = new Stats();`
