### ISSUE TITLE
The build is incompatible with ES module import

### ISSUE THREAD

**Issue by aurium** [mrdoob/stats.js#120]
Tring this:
```js
import('https://unpkg.com/stats.js@0.17.0/build/stats.min.js').then(()=> ...)
```
Will fail in the beginning of the script at `f.Stats = e()`, where f is `this`.

The error message is: `Uncaught (in promise) TypeError: can't access property "Stats", f is undefined`

**Comment by mrdoob** [comment]
```js
import('https://unpkg.com/stats.js@0.17.0/build/stats.module.js').then(()=> ...)
```

**Comment by aurium** [comment]
Hi @mrdoob, it finds no `stats.module.js` inside https://unpkg.com/browse/stats.js@0.17.0/build/

I'm reading the https://unpkg.com/browse/stats.js@0.17.0/package.json and I don't see how it builds `stats.module.js`. I think this feature was missed. Did I get it right?
