### ISSUE TITLE
firefox does not show memory panel

### ISSUE THREAD

**Issue by ManishJu** [mrdoob/stats.js#121]
`stats.showPanel(2) ` does not work on firefox
`stats.showPanel(1) ` & `stats.showPanel(0) ` work

**Comment by mrdoob** [comment]
Firefox doesn't support `performance.memory`.

<img width="169" alt="Screen Shot 2021-08-19 at 5 15 26 PM" src="https://user-images.githubusercontent.com/97088/130094740-f3bc96bf-0d60-441d-8808-c7be138f0fbe.png">
