### ISSUE TITLE
option for using performance.now() instead of Date.now()

### ISSUE THREAD

**Issue by yutongp** [mrdoob/stats.js#22]
performance.now(), introduced in HTML5, is a measurement of floating point milliseconds, so it is more accurate than Date.now() and it doesn't not skewed when the system time changes.
It could be a good choice for HTML5 web app frame rate measurement. 
Therefore, if there is an option to enable using performance.now() instead of Date.now() to measure the time, that will be really nice.
Thank you.

**Comment by mrdoob** [comment]
Implemented: #44
