### ISSUE TITLE
Please publish to NPM

### ISSUE THREAD

**Issue by iammerrick** [mrdoob/stats.js#32]
Now that you support CommonJS we would love this library on NPM. :-D

**Comment by schickling** [comment]
+1

**Comment by SandroMartis** [comment]
+1

The one that exists in npm is outdated.

**Comment by toxicFork** [comment]
+1

**Comment by kevzettler** [comment]
Who is maintaining the NPM module? It should be tied to this repo its out of date

https://www.npmjs.com/~lmacsen#packages
liviu@ideveloper.ro
@lmacsen on npm

**Comment by lmacsen** [comment]
@kevzettler I just updated the module to the latest version.

I made stats.js NPM module few months ago to use it in some projects and I forgot him. I never thought that someone else uses it.

I would like maintain this NPM module and update it every time from now.
But if any stats.js developer want to maintain this module, just let me know.

Thank you.

**Comment by mrdoob** [comment]
@lmacsen Wouldn't mind updating the package myself. Would it be possible to become the owner of the package? https://www.npmjs.com/~mrdoob

**Comment by kevzettler** [comment]
@lmacsen +1 for @mrdoob  maintaining

**Comment by toxicFork** [comment]
+1 it just makes more sense

**Comment by lmacsen** [comment]
@mrdoob

Sorry for the late. I added you as unique owner of stats.js NPM package.
I hope you will keep updated and thank you for all your great work!

**Comment by AdamBurgess** [comment]
Does the NPM package need the closure compiler .jar? It takes up quite a lot of space.

**Comment by thiphariel** [comment]
@mrdoob Hi. Can you add a webhook or something to auto publish update when you release to github ? The npm package is still in REVISION 12, github one's is 14.

Thanks.

**Comment by mrdoob** [comment]
Done!

**Comment by thiphariel** [comment]
Thanks :)
