### ISSUE TITLE
Problem when ms exceeds 300

### ISSUE THREAD

**Issue by adriankb** [mrdoob/stats.js#43]
This is a good tool.

But I have tried to use to to record some longer running javascript (not animations) and it starts creating negative height bars :)

If I get time I'll look at adapting the code, but it is a work project and time will get prioritised elsewhere I fear.

Cheers.

**Comment by mrdoob** [comment]
Oh, I forgot to `Math.min()` the value sent to `update()`...

**Comment by mrdoob** [comment]
Wait. I can't reproduce. Could you share a link where that happens?

**Comment by adriankb** [comment]
Thanks for the response. Unfortunately I don't have the code anymore that I was working on.
