### ISSUE TITLE
stats window don't refresh even the source code of html file has updated?

### ISSUE THREAD

**Issue by zhengjiezxxy** [mrdoob/stats.js#49]
This website is ok.
http://airtightinteractive.com/demos/js/cubes/

But the following site is just a clone of the above site, is not ok.
http://10.28.27.104/WebGL_Cubes_Demo/WebGL_Cubes_Demo.htm

What's the problem, I cannot figure it out.

**Comment by mrdoob** [comment]
Sorry, I can't offer user support.
