### ISSUE TITLE
Adding user defined panels

### ISSUE THREAD

**Issue by ubershmekel** [mrdoob/stats.js#50]
Hi @mrdoob would a pull request that enables users to add panels be useful to this project?

I'm making a game and I wanted to measure the `requestAnimationFrame` frequency alongside the server state update tick rate. A fourth performance panel seems like a good place to put it. I'm imagining a `createGraphPanel(id, fg, bg)` exported method that returns an object that has a `updateGraph(value)` method. Then `updateGraph` would take care of the `min` and `max` logic and text as well.

**Comment by mrdoob** [comment]
Hmm, that could be interesting yeah.

**Comment by ubershmekel** [comment]
It took `Stats.js` down from 185 lines to 174.

https://github.com/mrdoob/stats.js/pull/52

I'm not 100% certain this is the best possible API. But it seems the simplest that will do the job.

**Comment by mrdoob** [comment]
I like it! I was actually refactoring the whole thing this weekend and we have ended up doing a similar thing. I'll consolidate...

**Comment by ubershmekel** [comment]
Cool. Thanks.
