### ISSUE TITLE
package.json "main" points to missing file

### ISSUE THREAD

**Issue by brianchirls** [mrdoob/stats.js#54]
843cd66c4d9b42a635935558fc69c9cc3699ecd3 broke `require`'ing this code, as "main" now points to `"builds/stats.js"`, which does not exist.

I notice bower.json points to the minified file, which was presumably the intention here. It's more useful, I think, to point to the source file so people can choose to run their own minification process or leave it unminified for debugging.

Thanks.

**Comment by mrdoob** [comment]
Ops!

**Comment by mrdoob** [comment]
Thanks!
