### ISSUE TITLE
Customizing colors?

### ISSUE THREAD

**Issue by dy** [mrdoob/stats.js#58]
Hi @mrdoob!

I am using stats.js in [gl-spectrum](https://audio-lab.github.io/gl-spectrum), and I would really like to change panel’s color to match spectrum style. I see that now it is impossible.

Will that feature be welcomed in stats.js?

**Comment by dfcreative** [comment]
Whoa, not even a response

**Comment by mrdoob** [comment]
Sorry, I've been busy with [three.js](https://github.com/mrdoob/three.js/).
I think you should be able to change the colors with css.
