### ISSUE TITLE
stats's UI board affect page canvas's performance in mobile device

### ISSUE THREAD

**Issue by jasonChen1982** [mrdoob/stats.js#59]
my canvas program get bad performance with using stats in my mobile phone, I inspect this program in desktop chrome's timeline, I find broswer render page canvas and stats's UI board in a same composite layer. when i make stats's UI board in other composite layer , my canvas get normal.

**Comment by mrdoob** [comment]
> my canvas program get bad performance with using stats in my mobile phone, I inspect this program in desktop chrome's timeline, I find broswer render page canvas and stats's UI board in a same composite layer. 

Can you share some screenshots of that analysis?

**Comment by jasonChen1982** [comment]
in chrome can get following picture with timeline dev tool
##main canvas##
![image](https://cloud.githubusercontent.com/assets/8683772/16369669/b6fd5ffc-3c6b-11e6-9d1a-edad6a302de2.png)
##stats's UI board##
![image](https://cloud.githubusercontent.com/assets/8683772/16369677/d5d9ed8c-3c6b-11e6-8d35-7ac7a0fb00ea.png)
they in same composite layer 'canvas#canvas',and next picture was shot frome my mobile phone.
![image](https://cloud.githubusercontent.com/assets/8683772/16370298/1fff6342-3c71-11e6-8a94-1de1b10acdce.png)


by using css3d transform to trigger broswer generate a composite layer for stats's UI board. 
![image](https://cloud.githubusercontent.com/assets/8683772/16370421/f9de4998-3c71-11e6-9572-8e37e2c43a30.png)

**Comment by jasonChen1982** [comment]
when i used css3d transform to trigger a composite layer for stats's UI board,i get following screenshot. 

![image](https://cloud.githubusercontent.com/assets/8683772/16370480/96da5124-3c72-11e6-88aa-ff9fad9c1844.png)

**Comment by mrdoob** [comment]
I think this was more of a browser issue.
