### ISSUE TITLE
Need a way to determine when stats have updated

### ISSUE THREAD

**Issue by brianchirls** [mrdoob/stats.js#64]
The canvas is only updated once every second. Since there is no way to determine when the update happens, once has to assume it's happening on every frame.

I have some use cases where I need to view the stats canvas as a texture for three.js, specifically for webvr so I can see the frame rate inside the HMD. It would be nice if I didn't have to update the texture on every frame. Also, there are some cases where I want to use the stats as a texture but don't want to redraw on every frame because the camera and scene are static. So a render should only be necessary after the one-second interval update.

I'm happy to do this myself and make a pull request, but I'd like some feedback on how to do it so I don't waste my time. I can think of a couple options:
1. dispatch an event on update
2. add a `lastUpdate` property that's either the time stamp of the most recent update or an ever-incrementing counter

I think I prefer option 2.

**Comment by mrdoob** [comment]
Sorry, I think this is out of scope.
It would be better to recreate stats.js in webgl/three.js for your use case instead.
