### ISSUE TITLE
should device pixel ratio be rounded up?

### ISSUE THREAD

**Issue by iambumblehead** [mrdoob/stats.js#69]
https://github.com/mrdoob/stats.js/blob/master/src/Stats.js#L115

Using Firefox on different devices results in fuzzy Stats.js text. Using Math.ceil to define `PR` results in sharper looking text.

On the device I'm typing into now,
- Firefox devicePixelRatio: `1.3953487873077393`, 
- Chrome devicePixelRatio: `1.5`.

**Comment by mrdoob** [comment]
Hmm... I'm not sure...
