### ISSUE TITLE
mydiv.appendChild(stats.dom) places stats on document.body

### ISSUE THREAD

**Issue by backspaces** [mrdoob/stats.js#76]
In my code, I place stats as a child of mydiv rather than document.body.
But stats still appears on the top left of the page, as if I had used document.body.appendchild(stats)

Using chrome devtools, the stats div (stats.dom & stats.domElement) does appear to be in mydiv.children. And stats.dom.parentElement/Node are both mydiv. Yet the stats widget is at the page top-left.

Possibly I need to have mydiv have a style that makes sure the stats div places itself correctly?

**Comment by backspaces** [comment]
Maybe this is the problem:
stats.dom.style.position is "fixed". Maybe absolute?

**Comment by mrdoob** [comment]
Did you figured out?

**Comment by backspaces** [comment]
>
> Did you figured out?


Not yet. I saw the style was position: fixed. I remembered Three examples/
had stats in what appeared to be a separate div but it turned out to be an
iframe.

I tried changing the stats style to absolute after creating it, which
should have worked but didn't.

My css-fu is not that great, maybe my div needs to have some css
configuration to make the absolute work correctly.

Mainly I need to know if I should be able to make it work. We're not in a
huge rush, I'll let you know if we have any success with a more complete
investigation.

**Comment by mrdoob** [comment]
I think`position: fixed` (or `position: absolute`) is not enough.
You also need to set `top: 0, left: 0`.

**Comment by aatishb** [comment]
In case it helps anybody, I think the issue is that when stats.js loads, it rewrites any existing CSS properties you apply to it. I fixed this by changing

`c.style.cssText="position:absolute;top:0;left:0;cursor:pointer;opacity:0.9;z-index:10000"`
to
`c.style.cssText="position:relative;top:0;left:0;cursor:pointer;opacity:0.9;z-index:10000"`

in the stats.min.js file
