### ISSUE TITLE
Add the ability to record stats to somewhere

### ISSUE THREAD

**Issue by jwir3** [mrdoob/stats.js#83]
In our app testing, it would be really nice if we could somehow preserve the output of stats.js, perhaps as a recording to `localStorage`, or even an option to download a file. The idea would be that you could choose, when stats was setup, whether to preserve data to a `localStorage` variable or to only save it for a specific run, and then add an API to retrieve this data. Additionally, we could choose how many samples to store for any given run.

For example, what we'd like is to have an array of samples, stored in memory, and then either persist it to `localStorage` every `n` samples, or allow the user to click and download it. This would give a JSON version of the raw samples, which could then be used for future performance analysis.

**Comment by MasterJames** [comment]
Sounds good. As I'vé suggested before, I believe you need stats integrated into an optimization system that adjusts parameters on the scene depending on complex issues. For instance changing shadow map depth aka res. based on its projections distance from camera and other parameters obviously depending on the fps being achieved per device, so as you move around in a scene or even turn you pov these parameters per object, light, textire, shadow etc. Auto adjust in real time to provide optimal FPS depending on user preference as well. 
THREE.js is unfortunately not the layer to add such complexity. The stats thing?  Is fine as is laughable and legacy IMHO. It's replaceable and super simple. The real issues are far beyond the core level. Clara said they had to do something like that internally too. 
I also thought it would be cool if there was a modular injector system to enhance three.js with such 3rd party layers but as ive alao pointed out that itself would probably add too much more to manage in the repo. But again just putting it out there. So... Add ability to merge PRs that are injected on top of 3js when desired. Add a real time FPS optimization system that asks each object via injected API to adjust settings or switch to different states/geo/versions (cause its all baked for GL and not dynamic geo etc.) to make FPS or image-quality a user use-case preference. Also adding the ability to create objects by passing a single object with arguments in object form, is another simple rejected PR (just checks 1st arg for constructor Object so harmless) of mine that makes 3js more modern, for a reactive and nosql database way of thinking.
Alas it seems only a permanent referenced fork is within management's vision at this time (keep it simple in the core Kaos control policy). 
THREEjs is the way forward. I appreciate everybody's ideas and contributions. Long live THREEjs!

**Comment by 1-14x0r** [comment]
as much as i love stats.js why not just use the built in performance monitor that records the running application within the debug toolpanel. You could also add in some skeleton functions and calls to have them log into the monitor..

**Comment by mrdoob** [comment]
Sorry, seems a bit out of scope for the widget.

**Comment by NathanBWaters** [comment]
To follow up on this, is there any tooling out there for recording canvas performance and comparing the saved benchmarks?

**Comment by ZoeDreams** [comment]
> To follow up on this, is there any tooling out there for recording canvas performance and comparing the saved benchmarks?

well actually yes. this is build into chrome dev tools

https://developer.chrome.com/devtools/docs/profiles

**Comment by NathanBWaters** [comment]
Thanks @ZoeDreams!
