### ISSUE TITLE
Stats does not display text

### ISSUE THREAD

**Issue by wdanilo** [mrdoob/stats.js#85]
Hi!
I'm using the newest stats version, plugged it according to docs and it seems eveything works, but text. I see graphs that change according to how heavy the computations are but i dont see any text above the graphs - there is just empty space where the text should appear. Is it a known bug or am I doing something wrong.

EDIT: I just checked it under firefox and the texts are there, so it seems like a chrome-related issue. Its a 63.0.3239.70 (Official Build) beta (64-bit) @ Gentoo Linux.

**Comment by mrdoob** [comment]
Sounds like a browser issue indeed.
Please, report to Chrome instead.
