### ISSUE TITLE
dom or domElement ? 

### ISSUE THREAD

**Issue by nukadelic** [mrdoob/stats.js#89]
Hey @mrdoob, great tool. I was having trouble accessing the stats.dom variable as presented in your example. On the other hand domElement works just fine (r16). Also I have switched from r17 since the Stats class will be undefined for some reason.

Language: TypeScript
CDN r17: [cdnjs.com](https://cdnjs.cloudflare.com/ajax/libs/stats.js/r17/Stats.min.js)
IDE: [stackblitz.com](stackblitz.com)

----

[edit] when opening the cdn link above in a new type it will output the following: 
`// Error: Unexpected token: punc ({)`

**Comment by Nektro** [comment]
It seems the minified version was improperly compiled for r17. The normal `js` file is intact for `r17`. If you use `r16` and `domElement` it should work properly.
