### ISSUE TITLE
Bookmarklet is no longer working

### ISSUE THREAD

**Issue by FMS-Cat** [mrdoob/stats.js#92]
![image](https://user-images.githubusercontent.com/7824814/48460033-26a0e700-e810-11e8-86b7-0494bf1c90b2.png)

**Comment by mrdoob** [comment]
I guess I can do a `gh-page`?

**Comment by mrdoob** [comment]
Actually, the issue is that github.com doesn't allow bookmarklets. If you try the bookmarklet in http://mrdoob.com it works.

I've updated the bookmarklet with a non-rawgit.com link though.

Thanks!
