### ISSUE TITLE
jsdoc annotation might be helpful

### ISSUE THREAD

**Issue by ixtli** [mrdoob/stats.js#95]
```js
import Stats from "stats-js";

/**
 * @type {{begin: function(): void, end: function(): void, showPanel:
 *   function(number): void, dom: HTMLElement}}
 */
export const stats = new Stats();
```

I'm using this in a webpack application and the following allows me webstorm to highlight automatically. Doesn't really require anything except leaving a block comment on the top level object and the editors should do the rest.

**Comment by mrdoob** [comment]
Sorry, not a fan of jsdoc. It pollutes the code.
