### ISSUE TITLE
(Question) How can I align the window on bottom border?

### ISSUE THREAD

**Issue by HTLife** [mrdoob/stats.js#99]
Although I setup 
this.stats.domElement.style.bottom = '0px'
I still cannot align the window to bottom.
How can I do?

**Comment by killroy42** [comment]
add `style.position = `fixed`;` as well.

**Comment by HTLife** [comment]
This setting didn't really help in my case.
I finally solve it with Vue.js variable `window.width` and reset the window position when resizing.
